- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
    
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart Nginx
  service:
    name: nginx
    state: restarted
